<a href="https://colab.research.google.com/github/ldang64/COGS108_Repo/blob/main/DataCheckpoint_group088.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# COGS 108 - Data Checkpoint

# Names
- Lisa Dang
- Danny Ha
- Justin Le
- Destynee Tau
- Pauline Thach

<a id='research_question'></a>
# Research Question

How does a person’s racial background and personal qualities affect their desirability as a potential partner? Do factors such as similar interests and personality traits make a more positive first impression, therefore increasing the liklihood of attraction?

# Dataset(s)

We will be analyzing data obtained from a speed dating study conducted by Columbia Business School professors, Ray Fisman and Sheena Iyengar, who wanted to observe the individual decisions that went into selecting a possible mate:


Gender Differences in Mate Selection: Evidence From a Speed Dating Experiment
*   Source: http://www.stat.columbia.edu/~gelman/arm/examples/speed.dating/
*   Open in .xlsx / .csv: https://docs.google.com/spreadsheets/d/1mRUc5uxDuC8OxIeBv9rv8drtHGdE2I7dVLltpCr20yI/edit?usp=sharing
*   Number of observations: ~ 8,000 adults
*   Variables: Attractiveness, sincerity, fun, ambition, intelligence, shared interests, racial/ethnic background
*   Method: Data was collected from students at Columbia University recruited by e-mails and fliers. Trials took place during speed dating events held at popular restaurants near campus. Participants would rank certain attributes of their dates on paper and determine if they would be a match.

This dataset has over 8,000 observations gathered over a course of two years (2002-2004). In this experiment, participants at Columbia University were asked to sign up for various Speed Dating events taking place at bars and restaurants near campus. To keep the environmental setting constant, trials at each location kept the same table arrangements, music, and lighting to reduce external factors from influencing outcomes. 

The study provided us with approximately 200 data points for each observation in relation to each participant’s racial background, field of study, and interests. Using this information, our group will be able to answer our research questions on whether certain qualities of a person and similarities increase the likelihood of finding a match. For this particular dataset, we will be reducing the amount of data points set out for us so that we can simplify the data and focus on traits of greater importance to our research. For instance, we can remove variables that include income, zip code, tuition, and etc. for variables that we want to delve into for our question and hypothesis such as race, career, activities, and field of study.

# Setup

In [ ]:
# Imported packages used to create the dataset
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import csv
import io

# Data Cleaning

### **Dataset 1**: Speed Dating dataset
Importing the data to create the table:

In [ ]:
# Assign a variable to the speed dating data file to be read 
dataURL = "https://raw.githubusercontent.com/COGS108/group088_wi21/main/Speed%20Dating%20Dataset/SpeedDatingDataset.csv?token=ASMP55MJ44PLDKVUGRO3NJLAF5SYY"
speedDating_df = pd.read_csv(dataURL)

# Take a look at the original dataset
speedDating_df.head()

   gender  match  int_corr  samerace  ...  sinc5_3  intel5_3  fun5_3  amb5_3
0       0      0      0.14         0  ...      NaN       NaN     NaN     NaN
1       0      0      0.54         0  ...      NaN       NaN     NaN     NaN
2       0      1      0.16         1  ...      NaN       NaN     NaN     NaN
3       0      1      0.61         0  ...      NaN       NaN     NaN     NaN
4       0      1      0.21         0  ...      NaN       NaN     NaN     NaN

[5 rows x 175 columns]

**DATA** **CLEANING**: Get each of your datasets into a usable (likely, tidy) format. Briefly explain what steps you had to take before you were able to use the datasets you chose to answer your question of interest.

How 'clean' is the data?
What did you have to do to get the data into a usable format? (If you did nothing, how did you determine there was nothing to do?)
What pre-processing steps that were required for your methods (for example, checking data distributions and performing any transformations that may be required)

To clean this dataset, we eliminated variables that were outside the scope of our research question, since the dataset was expansive to begin with. We also modified the initial representations of results for clarity (for instance, a value of '0' in a certain category corresponded to an answer of 'No', so we converted '0' to 'No'). Many of the operations we performed were of this "housekeeping" nature.

This particular dataset was relatively clean and we probably could have used it without modification. Minor tweaks, as previously described, were done to make future data analysis easier.

In [ ]:
## Cleaning dataset 1

# specify certain variables to include
speedDating_df = speedDating_df[['gender', 'match', 'age_o', 'samerace', 'race_o', 'goal', 'date', 'dec_o','attr_o', 'sinc_o', 'intel_o', 'fun_o', 'amb_o', 'shar_o','int_corr']]

#change column variable names to have easier understanding
speedDating_df.rename(columns={'gender':'Gender'}, inplace=True)
speedDating_df.rename(columns={'match':'Match?'}, inplace=True)
speedDating_df.rename(columns={'age_o':'Age'}, inplace=True)
speedDating_df.rename(columns={'samerace':'Same race?'}, inplace=True)
speedDating_df.rename(columns={'race_o':'Race'}, inplace=True)
speedDating_df.rename(columns={'goal':'Goal'}, inplace=True)
speedDating_df.rename(columns={'date':'Frequency of dates'}, inplace=True)
speedDating_df.rename(columns={'dec_o':'Meet again?'}, inplace=True)
speedDating_df.rename(columns={'attr_o':'Attractiveness'}, inplace=True)
speedDating_df.rename(columns={'sinc_o':'Sincerity'}, inplace=True)
speedDating_df.rename(columns={'intel_o':'Intelligence'}, inplace=True)
speedDating_df.rename(columns={'fun_o':'Fun'}, inplace=True)
speedDating_df.rename(columns={'amb_o':'Ambition'}, inplace=True)
speedDating_df.rename(columns={'shar_o':'Shared Interests'}, inplace=True)

#replaces current '0' & '1' values with 'Yes' & 'No' where appropriate
speed_bool = speedDating_df['Same race?'].replace({0: 'No', 1: 'Yes'})
speedDating_df['Same race?'] = speed_bool.replace({0: 'No', 1: 'Yes'})

speed_bool = speedDating_df['Match?'].replace({0: 'No', 1: 'Yes'})
speedDating_df['Match?'] = speed_bool.replace({0: 'No', 1: 'Yes'})

speed_bool = speedDating_df['Meet again?'].replace({0: 'No', 1: 'Yes'})
speedDating_df['Meet again?'] = speed_bool.replace({0: 'No', 1: 'Yes'})

#replaces current '0' & '1' values in the gender column
speed_bool = speedDating_df['Gender'].replace({0: 'F', 1: 'M'})
speed_bool
speedDating_df['Gender'] = speed_bool.replace({0: 'F', 1: 'M'})

#change variable values from float to int where appropriate
speedDating_df['Age'] = speedDating_df['Age'].astype('Int64')
speedDating_df['Race'] = speedDating_df['Race'].astype('Int64')
speedDating_df['Goal'] = speedDating_df['Goal'].astype('Int64')
speedDating_df['Frequency of dates'] = speedDating_df['Frequency of dates'].astype('Int64')

speedDating_df

     Gender Match?  Age Same race?  ...   Fun  Ambition  Shared Interests int_corr
0         F     No   27         No  ...   8.0       8.0               6.0     0.14
1         F     No   22         No  ...   7.0       7.0               5.0     0.54
2         F    Yes   22        Yes  ...  10.0      10.0              10.0     0.16
3         F    Yes   23         No  ...   8.0       9.0               8.0     0.61
4         F    Yes   24         No  ...   6.0       9.0               7.0     0.21
...     ...    ...  ...        ...  ...   ...       ...               ...      ...
8373      M     No   26         No  ...   2.0       6.0               5.0     0.64
8374      M     No   24         No  ...   3.0       7.0               2.0     0.71
8375      M     No   29         No  ...   2.0       2.0               1.0    -0.46
8376      M     No   22         No  ...   5.0       3.0               6.0     0.62
8377      M     No   22         No  ...   7.0       7.0               7.0     0.01

[8378 rows x 15 columns]

# Project Proposal (updated)

| Meeting Date  | Meeting Time| Completed Before Meeting  | Discuss at Meeting |
|:---:|:---:|:---|:---|
| 1/24  |  8 PM | Read & Think about COGS 108 expectations; brainstorm topics/questions  | Determine best form of communication; Discuss and decide on final project topic; discuss hypothesis; begin background research | 
| 1/27  |  10 PM |  Do background research on topic | Discuss ideal dataset(s) and ethics; draft project proposal | 
| 1/29  | 10 AM  | Edit, finalize, and submit proposal; Search for datasets  | Discuss Wrangling and possible analytical approaches; Assign group members to lead each specific part   |
| 2/1  | 10 AM  | Project setup | 	Possible additional changes to the setup   |
| 2/8  | 6 PM  | 	Import & Wrangle Data, EDA) | Review/Edit wrangling/EDA; Discuss Analysis Plan |
| 2/15  | 6 PM  | Coding | 	Discuss/edit Analysis; Complete project check-in |
| 2/22  | 6 PM  | Data Analysis | Error checking |
| 3/1  | 6 PM  | Descriptive section | Spellcheck and proofread |
| 3/8  | 6 PM  | Summary and Conclusion | 	Discuss/edit full project |
| 3/17 | Before 11:59 PM  | NA | 	Turn in Final Project & Group Project Surveys |